version: "3.7"

services:
  app:
    image: php
    container_name: integrador-backend
    command: php -S 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo