version: "3.7"

services:
  app:
    image: integrador_backend/php:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: integrador_backend
    command: php -S 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo
  db:
    image: mysql
    container_name: integrador_backend_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=integrador
      - TZ=America/Sao_Paulo
networks:
  default:
    external:
      name: integrador_backend_network